/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : ESP8266_RxBuf.c
**     Project     : clay_5g_demo_esp8266
**     Processor   : MK20DX256VLH7
**     Component   : RingBufferUInt8
**     Version     : Component 01.003, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-09-14, 14:17, # CodeGen: 2
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         Put             - byte ESP8266_RxBuf_Put(byte elem);
**         Get             - byte ESP8266_RxBuf_Get(byte *elemP);
**         NofElements     - byte ESP8266_RxBuf_NofElements(void);
**         NofFreeElements - byte ESP8266_RxBuf_NofFreeElements(void);
**         Init            - void ESP8266_RxBuf_Init(void);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2012, all rights reserved.
**     This an open source software of an embedded component for Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file ESP8266_RxBuf.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup ESP8266_RxBuf_module ESP8266_RxBuf module documentation
**  @{
*/         

/* MODULE ESP8266_RxBuf. */

#include "ESP8266_RxBuf.h"

static uint8_t ESP8266_RxBuf_buffer[ESP8266_RxBuf_BUF_SIZE]; /* ring buffer */
static uint8_t ESP8266_RxBuf_inIdx;  /* input index */
static uint8_t ESP8266_RxBuf_outIdx; /* output index */
static uint8_t ESP8266_RxBuf_inSize; /* size of input data */
/*
** ===================================================================
**     Method      :  ESP8266_RxBuf_Put (component RingBufferUInt8)
**     Description :
**         Puts a new element into the buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**         elem            - New element to be put into the buffer
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
byte ESP8266_RxBuf_Put(byte elem)
{
  byte res = ERR_OK;

  EnterCritical();
  if (ESP8266_RxBuf_inSize==ESP8266_RxBuf_BUF_SIZE) {
    res = ERR_TXFULL;
  } else {
    ESP8266_RxBuf_buffer[ESP8266_RxBuf_inIdx] = elem;
    ESP8266_RxBuf_inSize++;
    ESP8266_RxBuf_inIdx++;
    if (ESP8266_RxBuf_inIdx==ESP8266_RxBuf_BUF_SIZE) {
      ESP8266_RxBuf_inIdx = 0;
    }
  }
  ExitCritical();
  return res;
}

/*
** ===================================================================
**     Method      :  ESP8266_RxBuf_Get (component RingBufferUInt8)
**     Description :
**         Removes an element from the buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**       * elemP           - Pointer to where to store the received
**                           element
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
byte ESP8266_RxBuf_Get(byte *elemP)
{
  byte res = ERR_OK;

  EnterCritical();
  if (ESP8266_RxBuf_inSize==0) {
    res = ERR_RXEMPTY;
  } else {
    *elemP = ESP8266_RxBuf_buffer[ESP8266_RxBuf_outIdx];
    ESP8266_RxBuf_inSize--;
    ESP8266_RxBuf_outIdx++;
    if (ESP8266_RxBuf_outIdx==ESP8266_RxBuf_BUF_SIZE) {
      ESP8266_RxBuf_outIdx = 0;
    }
  }
  ExitCritical();
  return res;
}

/*
** ===================================================================
**     Method      :  ESP8266_RxBuf_NofElements (component RingBufferUInt8)
**     Description :
**         Returns the actual number of elements in the buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of elements in the buffer.
** ===================================================================
*/
byte ESP8266_RxBuf_NofElements(void)
{
  return ESP8266_RxBuf_inSize;
}

/*
** ===================================================================
**     Method      :  ESP8266_RxBuf_NofFreeElements (component RingBufferUInt8)
**     Description :
**         Returns the actual number of free elements/space in the
**         buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of elements in the buffer.
** ===================================================================
*/
byte ESP8266_RxBuf_NofFreeElements(void)
{
  return (byte)(ESP8266_RxBuf_BUF_SIZE-ESP8266_RxBuf_inSize);
}

/*
** ===================================================================
**     Method      :  ESP8266_RxBuf_Init (component RingBufferUInt8)
**     Description :
**         Initializes the data structure
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void ESP8266_RxBuf_Init(void)
{
  ESP8266_RxBuf_inIdx = 0;
  ESP8266_RxBuf_outIdx = 0;
  ESP8266_RxBuf_inSize = 0;
}

/* END ESP8266_RxBuf. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
