/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : WIFI_GPIO0.h
**     Project     : Clay_C6_Firmware
**     Processor   : MK64FN1M0VLL12
**     Component   : GPIO_LDD
**     Version     : Component 01.128, Driver 01.08, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-02-18, 00:34, # CodeGen: 7
**     Abstract    :
**         The HAL GPIO component will provide a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL GPIO API will be simpler and more
**         portable to various microprocessors.
**     Settings    :
**          Component name                                 : WIFI_GPIO0
**          Port                                           : PTA
**          Port width                                     : 32 bits
**          Mask of allocated pins                         : 0x10000
**          Interrupt service/event                        : Enabled
**            Interrupt                                    : INT_PORTA
**            Interrupt priority                           : medium priority
**          Bit fields                                     : 1
**            Bit field                                    : 
**              Field name                                 : GPIO0
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : PTA16/SPI0_SOUT/UART0_CTS_b/UART0_COL_b/RMII0_TXD0/MII0_TXD0/I2S0_RX_FS/I2S0_RXD1
**                  Initial pin direction                  : Output
**                    Initial output state                 : 1
**                  Initial pin event                      : Disabled
**                  Lock initialization function           : no
**          Initialization                                 : 
**            Auto initialization                          : no
**            Event mask                                   : 
**              OnPortEvent                                : Enabled
**     Contents    :
**         Init                   - LDD_TDeviceData* WIFI_GPIO0_Init(LDD_TUserData *UserDataPtr);
**         SetPortEventCondition  - LDD_TError WIFI_GPIO0_SetPortEventCondition(LDD_TDeviceData *DeviceDataPtr,...
**         SetPortValue           - void WIFI_GPIO0_SetPortValue(LDD_TDeviceData *DeviceDataPtr,...
**         GetPortValue           - WIFI_GPIO0_TPortValue WIFI_GPIO0_GetPortValue(LDD_TDeviceData *DeviceDataPtr);
**         SetPortInputDirection  - void WIFI_GPIO0_SetPortInputDirection(LDD_TDeviceData *DeviceDataPtr,...
**         SetPortOutputDirection - void WIFI_GPIO0_SetPortOutputDirection(LDD_TDeviceData *DeviceDataPtr,...
**         SetFieldValue          - void WIFI_GPIO0_SetFieldValue(LDD_TDeviceData *DeviceDataPtr,...
**         GetFieldValue          - WIFI_GPIO0_TFieldValue WIFI_GPIO0_GetFieldValue(LDD_TDeviceData...
**         ClearFieldBits         - void WIFI_GPIO0_ClearFieldBits(LDD_TDeviceData *DeviceDataPtr,...
**         SetFieldBits           - void WIFI_GPIO0_SetFieldBits(LDD_TDeviceData *DeviceDataPtr,...
**         ToggleFieldBits        - void WIFI_GPIO0_ToggleFieldBits(LDD_TDeviceData *DeviceDataPtr,...
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file WIFI_GPIO0.h
** @version 01.08
** @brief
**         The HAL GPIO component will provide a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL GPIO API will be simpler and more
**         portable to various microprocessors.
*/         
/*!
**  @addtogroup WIFI_GPIO0_module WIFI_GPIO0 module documentation
**  @{
*/         

#ifndef __WIFI_GPIO0_H
#define __WIFI_GPIO0_H

/* MODULE WIFI_GPIO0. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "IO_Map.h"
#include "GPIO_PDD.h"
#include "PORT_PDD.h"

#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif 


/*! Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros. */
#define WIFI_GPIO0_PRPH_BASE_ADDRESS  0x400FF000U
  
/* Methods configuration constants - generated for all enabled component's methods */
#define WIFI_GPIO0_Init_METHOD_ENABLED /*!< Init method of the component WIFI_GPIO0 is enabled (generated) */
#define WIFI_GPIO0_SetPortEventCondition_METHOD_ENABLED /*!< SetPortEventCondition method of the component WIFI_GPIO0 is enabled (generated) */
#define WIFI_GPIO0_SetPortValue_METHOD_ENABLED /*!< SetPortValue method of the component WIFI_GPIO0 is enabled (generated) */
#define WIFI_GPIO0_GetPortValue_METHOD_ENABLED /*!< GetPortValue method of the component WIFI_GPIO0 is enabled (generated) */
#define WIFI_GPIO0_SetPortInputDirection_METHOD_ENABLED /*!< SetPortInputDirection method of the component WIFI_GPIO0 is enabled (generated) */
#define WIFI_GPIO0_SetPortOutputDirection_METHOD_ENABLED /*!< SetPortOutputDirection method of the component WIFI_GPIO0 is enabled (generated) */
#define WIFI_GPIO0_SetFieldValue_METHOD_ENABLED /*!< SetFieldValue method of the component WIFI_GPIO0 is enabled (generated) */
#define WIFI_GPIO0_GetFieldValue_METHOD_ENABLED /*!< GetFieldValue method of the component WIFI_GPIO0 is enabled (generated) */
#define WIFI_GPIO0_ClearFieldBits_METHOD_ENABLED /*!< ClearFieldBits method of the component WIFI_GPIO0 is enabled (generated) */
#define WIFI_GPIO0_SetFieldBits_METHOD_ENABLED /*!< SetFieldBits method of the component WIFI_GPIO0 is enabled (generated) */
#define WIFI_GPIO0_ToggleFieldBits_METHOD_ENABLED /*!< ToggleFieldBits method of the component WIFI_GPIO0 is enabled (generated) */

/* Events configuration constants - generated for all enabled component's events */
#define WIFI_GPIO0_OnPortEvent_EVENT_ENABLED /*!< OnPortEvent event of the component WIFI_GPIO0 is enabled (generated) */

/* Definition of bit field constants */
#define GPIO0 ((LDD_GPIO_TBitField)0)

/* Definition of implementation constants */
#define WIFI_GPIO0_ALLOCATED_PINS_MASK 0x00010000U /*!< Mask of all allocated pins from the port */
#define WIFI_GPIO0_MODULE_BASE_ADDRESS PTA_BASE_PTR /*!< Name of macro used as the base address */
#define WIFI_GPIO0_PORTCONTROL_BASE_ADDRESS PORTA_BASE_PTR /*!< Name of macro used as the base address */
#define WIFI_GPIO0_AVAILABLE_EVENTS_MASK LDD_GPIO_ON_PORT_EVENT /*!< Mask of all available events */
#define WIFI_GPIO0_FIELD_0_PIN_0 LDD_GPIO_PIN_16 /*!< Constant for the pin in the field used in the method ConnectPin */
#define WIFI_GPIO0_GPIO0_START_BIT 16u /*!< Index of the starting bit of the bit field (0 represents LSB) */
#define WIFI_GPIO0_GPIO0_MASK 0x00010000u /*!< Mask of the bits allocated by the bit field (within the port) */
/* Representation of unaligned data value of the port.
   Unsigned integer of proper width depending on the size of the GPIO port allocated.
   Typically the value of n-th bit represents the data for the n-th pin within the port.
   Such value is not abstracted from the physical position of the bits within the port. */
typedef uint32_t WIFI_GPIO0_TPortValue;

/* Representation of right-aligned data value of the bit field.
   Typically the value of n-th bit represents the data of the n-th bit within the bit field (not within the port).
   There are used only so many lowest bits, as it is denoted by the width of the bit field.
   Such value is abstracted from the physical position of the bit field pins within the port.
   Equals to the type <compId>_TPortValue. */
typedef WIFI_GPIO0_TPortValue WIFI_GPIO0_TFieldValue;



/*
** ===================================================================
**     Method      :  WIFI_GPIO0_Init (component GPIO_LDD)
*/
/*!
**     @brief
**         This method initializes the associated peripheral(s) and the
**         component internal variables. The method is called
**         automatically as a part of the application initialization
**         code.
**     @param
**         UserDataPtr     - Pointer to the RTOS device
**                           structure. This pointer will be passed to
**                           all events as parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* WIFI_GPIO0_Init(LDD_TUserData *UserDataPtr);

/*
** ===================================================================
**     Method      :  WIFI_GPIO0_SetPortEventCondition (component GPIO_LDD)
*/
/*!
**     @brief
**         This method defines condition of the [OnPortEvent] for
**         required pins of the port.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Mask            - Unaligned mask of bits to setting the
**                           event condition. Each port pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected pin, bit value 1 means
**                           selected pin. The bit 0 corresponds with
**                           the pin which has index 0 within the port,
**                           the bit 1 corresponds with the pin which
**                           has index 1 within the port, etc.
**     @param
**         Condition       - Defines conditions when event
**                           is invoked. Possible values are: 
**                           LDD_GPIO_DISABLED - Event doesn't invoke. 
**                           LDD_GPIO_LOW - Event when logic zero.
**                           LDD_GPIO_HIGH - Event when logic one.
**                           LDD_GPIO_RISING - Event on rising edge.
**                           LDD_GPIO_FALLING - Event on falling edge.
**                           LDD_GPIO_BOTH - Event on rising and falling
**                           edge. 
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_PARAM_MASK - Invalid pin mask.
**                           ERR_PARAM_CONDITION - Invalid condition.
*/
/* ===================================================================*/
LDD_TError WIFI_GPIO0_SetPortEventCondition(LDD_TDeviceData *DeviceDataPtr, WIFI_GPIO0_TPortValue Mask, LDD_GPIO_TEventCondition Condition);

/*
** ===================================================================
**     Method      :  WIFI_GPIO0_SetPortValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method writes the output data value to the port. Only
**         configured pins (through all of bit fields in this component)
**         are affected.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Value           - Unaligned data value to write to the
**                           port. The bit 0 corresponds with the pin
**                           which has index 0 within the port, the bit
**                           1 corresponds with the pin which has index
**                           1 within the port, etc. Only configured
**                           pins (through all of bit fields in this
**                           component) are affected.
*/
/* ===================================================================*/
void WIFI_GPIO0_SetPortValue(LDD_TDeviceData *DeviceDataPtr, WIFI_GPIO0_TPortValue Value);

/*
** ===================================================================
**     Method      :  WIFI_GPIO0_GetPortValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method returns the current port input data value. Only
**         configured pins (through all of bit fields in this component)
**         are returned.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Unaligned current port input data value
**                           masked for allocated pins of the port. The
**                           bit 0 corresponds with the pin which has
**                           index 0 within the port, the bit 1
**                           corresponds with the pin which has index 1
**                           within the port, etc. Only configured pins
**                           (through all of bit fields in this
**                           component) are returned. The others are
**                           zeros.
*/
/* ===================================================================*/
WIFI_GPIO0_TPortValue WIFI_GPIO0_GetPortValue(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  WIFI_GPIO0_SetPortInputDirection (component GPIO_LDD)
*/
/*!
**     @brief
**         This method sets the specified pins of the port to the input
**         direction. Only configured pins (through all of bit fields
**         in this component) are affected.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Mask            - Mask of bits to setting the input
**                           direction. Each port pin has corresponding
**                           bit in the mask. Bit value 0 means not
**                           selected bit, bit value 1 means selected
**                           bit. The bit 0 corresponds with the pin
**                           which has index 0 within the port, the bit
**                           1 corresponds with the pin which has index
**                           1 within the port, etc. Only configured
**                           pins (through all of bit fields in this
**                           component) are affected.
*/
/* ===================================================================*/
void WIFI_GPIO0_SetPortInputDirection(LDD_TDeviceData *DeviceDataPtr, WIFI_GPIO0_TPortValue Mask);

/*
** ===================================================================
**     Method      :  WIFI_GPIO0_SetPortOutputDirection (component GPIO_LDD)
*/
/*!
**     @brief
**         This method sets the specified pins of the port to the
**         output direction. The specified pins of the port will be
**         driven to specified states. Only configured pins (through
**         all of bit fields in this component) are affected.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Mask            - Mask of bits to setting the output
**                           direction. Each port pin has corresponding
**                           bit in the mask. Bit value 0 means not
**                           selected bit, bit value 1 means selected
**                           bit. The bit 0 corresponds with the pin
**                           which has index 0 within the port, the bit
**                           1 corresponds with the pin which has index
**                           1 within the port, etc. Only configured
**                           pins (through all of bit fields in this
**                           component) are affected.
**     @param
**         Value           - Unaligned port data value to appear on
**                           the specified port pins after they have
**                           been switched to the output direction.
*/
/* ===================================================================*/
void WIFI_GPIO0_SetPortOutputDirection(LDD_TDeviceData *DeviceDataPtr, WIFI_GPIO0_TPortValue Mask, WIFI_GPIO0_TPortValue Value);

/*
** ===================================================================
**     Method      :  WIFI_GPIO0_SetFieldValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method sets the output data value of the specified bit
**         field.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Value           - Aligned data value to writting to the
**                           specified bit field. The bit 0 corresponds
**                           with the pin which has index 0 within the
**                           given bit field, the bit 1 corresponds with
**                           the pin which has index 1 within the given
**                           bit field, etc.
*/
/* ===================================================================*/
void WIFI_GPIO0_SetFieldValue(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, WIFI_GPIO0_TFieldValue Value);

/*
** ===================================================================
**     Method      :  WIFI_GPIO0_GetFieldValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method returns the current input data of the specified
**         field.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Field           - Bit field to reading. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @return
**                         - Aligned current port input value masked for
**                           allocated pins of the field. The bit 0
**                           corresponds with the pin which has index 0
**                           within the given bit field, the bit 1
**                           corresponds with the pin which has index 1
**                           within the given bit field, etc.
*/
/* ===================================================================*/
WIFI_GPIO0_TFieldValue WIFI_GPIO0_GetFieldValue(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field);

/*
** ===================================================================
**     Method      :  WIFI_GPIO0_ClearFieldBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method drives the specified bits of the specified bit
**         field to the inactive level.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Mask            - Aligned mask of bits to setting the
**                           inactive level. Each field pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the given
**                           bit field, the bit 1 corresponds with the
**                           pin which has index 1 within the given bit
**                           field, etc.
*/
/* ===================================================================*/
void WIFI_GPIO0_ClearFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, WIFI_GPIO0_TFieldValue Mask);

/*
** ===================================================================
**     Method      :  WIFI_GPIO0_SetFieldBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method drives the specified bits of the specified bit
**         field to the active level.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Mask            - Aligned mask of bits to setting the
**                           active level. Each field pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the given
**                           bit field, the bit 1 corresponds with the
**                           pin which has index 1 within the given bit
**                           field, etc.
*/
/* ===================================================================*/
void WIFI_GPIO0_SetFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, WIFI_GPIO0_TFieldValue Mask);

/*
** ===================================================================
**     Method      :  WIFI_GPIO0_ToggleFieldBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method inverts the specified bits of the specified bit
**         field to other level.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Mask            - Aligned mask of bits to inverting the
**                           current level. Each field pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the given
**                           bit field, the bit 1 corresponds with the
**                           pin which has index 1 within the given bit
**                           field, etc.
*/
/* ===================================================================*/
void WIFI_GPIO0_ToggleFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, WIFI_GPIO0_TFieldValue Mask);

/*
** ===================================================================
**     Method      :  WIFI_GPIO0_Interrupt (component GPIO_LDD)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
/* {Default RTOS Adapter} ISR function prototype */
PE_ISR(WIFI_GPIO0_Interrupt);

/* END WIFI_GPIO0. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

#endif
/* ifndef __WIFI_GPIO0_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
