/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : WIFI_XPD_DCDC_INTERRUPT.c
**     Project     : Clay_C6_Firmware
**     Processor   : MK64FN1M0VLL12
**     Component   : GPIO_LDD
**     Version     : Component 01.128, Driver 01.08, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-02-27, 20:18, # CodeGen: 17
**     Abstract    :
**         The HAL GPIO component will provide a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL GPIO API will be simpler and more
**         portable to various microprocessors.
**     Settings    :
**          Component name                                 : WIFI_XPD_DCDC_INTERRUPT
**          Port                                           : PTE
**          Port width                                     : 32 bits
**          Mask of allocated pins                         : 0x2000000
**          Interrupt service/event                        : Enabled
**            Interrupt                                    : INT_PORTE
**            Interrupt priority                           : medium priority
**          Bit fields                                     : 1
**            Bit field                                    : 
**              Field name                                 : INTERRUPT
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : ADC0_SE18/PTE25/UART4_RX/I2C0_SDA/EWM_IN
**                  Initial pin direction                  : Input
**                  Initial pin event                      : Falling edge
**                  Lock initialization function           : no
**          Initialization                                 : 
**            Auto initialization                          : yes
**            Event mask                                   : 
**              OnPortEvent                                : Enabled
**     Contents    :
**         Init            - LDD_TDeviceData* WIFI_XPD_DCDC_INTERRUPT_Init(LDD_TUserData *UserDataPtr);
**         SetFieldValue   - void WIFI_XPD_DCDC_INTERRUPT_SetFieldValue(LDD_TDeviceData *DeviceDataPtr,...
**         GetFieldValue   - WIFI_XPD_DCDC_INTERRUPT_TFieldValue WIF...
**         ClearFieldBits  - void WIFI_XPD_DCDC_INTERRUPT_ClearFieldBits(LDD_TDeviceData *DeviceDataPtr,...
**         SetFieldBits    - void WIFI_XPD_DCDC_INTERRUPT_SetFieldBits(LDD_TDeviceData *DeviceDataPtr,...
**         ToggleFieldBits - void WIFI_XPD_DCDC_INTERRUPT_ToggleFieldBits(LDD_TDeviceData *DeviceDataPtr,...
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file WIFI_XPD_DCDC_INTERRUPT.c
** @version 01.08
** @brief
**         The HAL GPIO component will provide a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL GPIO API will be simpler and more
**         portable to various microprocessors.
*/         
/*!
**  @addtogroup WIFI_XPD_DCDC_INTERRUPT_module WIFI_XPD_DCDC_INTERRUPT module documentation
**  @{
*/         

/* MODULE WIFI_XPD_DCDC_INTERRUPT. */

#include "Events.h"
#include "WIFI_XPD_DCDC_INTERRUPT.h"
/* {Default RTOS Adapter} No RTOS includes */
#include "IO_Map.h"

#ifdef __cplusplus
extern "C" {
#endif 

typedef struct {
  WIFI_XPD_DCDC_INTERRUPT_TPortValue EventFlags; /* Holds event flags */
  LDD_TUserData *UserData;             /* RTOS device data structure */
} WIFI_XPD_DCDC_INTERRUPT_TDeviceData, *WIFI_XPD_DCDC_INTERRUPT_TDeviceDataPtr; /* Device data structure type */
/* {Default RTOS Adapter} Static object used for simulation of dynamic driver memory allocation */
static WIFI_XPD_DCDC_INTERRUPT_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC;
/* {Default RTOS Adapter} Global variable used for passing a parameter into ISR */
static WIFI_XPD_DCDC_INTERRUPT_TDeviceData * INT_PORTE__DEFAULT_RTOS_ISRPARAM;
/*
** ===================================================================
**     Method      :  WIFI_XPD_DCDC_INTERRUPT_Init (component GPIO_LDD)
*/
/*!
**     @brief
**         This method initializes the associated peripheral(s) and the
**         component internal variables. The method is called
**         automatically as a part of the application initialization
**         code.
**     @param
**         UserDataPtr     - Pointer to the RTOS device
**                           structure. This pointer will be passed to
**                           all events as parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* WIFI_XPD_DCDC_INTERRUPT_Init(LDD_TUserData *UserDataPtr)
{
  /* Allocate LDD device structure */
  WIFI_XPD_DCDC_INTERRUPT_TDeviceData *DeviceDataPrv;

  /* {Default RTOS Adapter} Driver memory allocation: Dynamic allocation is simulated by a pointer to the static object */
  DeviceDataPrv = &DeviceDataPrv__DEFAULT_RTOS_ALLOC;
  /* Save RTOS Device structure */
  DeviceDataPrv->EventFlags = 0x00U;   /* Clears stored events */
  DeviceDataPrv->UserData = UserDataPtr; /* Store the RTOS device structure */
  /* Interrupt vector(s) allocation */
  /* {Default RTOS Adapter} Set interrupt vector: IVT is static, ISR parameter is passed by the global variable */
  INT_PORTE__DEFAULT_RTOS_ISRPARAM = DeviceDataPrv;
  /* Enable device clock gate */
  /* SIM_SCGC5: PORTE=1 */
  SIM_SCGC5 |= SIM_SCGC5_PORTE_MASK;
  /* GPIOE_PDDR: PDD&=~0x02000000 */
  GPIOE_PDDR &= (uint32_t)~(uint32_t)(GPIO_PDDR_PDD(0x02000000));
  /* Initialization of pin routing */
  /* PORTE_PCR25: ISF=0,MUX=1 */
  PORTE_PCR25 = (uint32_t)((PORTE_PCR25 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x06)
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x01)
                ));
  /* PORTE_PCR25: ISF=1,IRQC=0x0A */
  PORTE_PCR25 = (uint32_t)((PORTE_PCR25 & (uint32_t)~(uint32_t)(
                 PORT_PCR_IRQC(0x05)
                )) | (uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_IRQC(0x0A)
                ));
  /* NVICIP63: PRI63=0x70 */
  NVICIP63 = NVIC_IP_PRI63(0x70);
  /* NVICISER1: SETENA|=0x80000000 */
  NVICISER1 |= NVIC_ISER_SETENA(0x80000000);
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_WIFI_XPD_DCDC_INTERRUPT_ID,DeviceDataPrv);
  return ((LDD_TDeviceData *)DeviceDataPrv);
}

/*
** ===================================================================
**     Method      :  WIFI_XPD_DCDC_INTERRUPT_SetFieldValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method sets the output data value of the specified bit
**         field.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Value           - Aligned data value to writting to the
**                           specified bit field. The bit 0 corresponds
**                           with the pin which has index 0 within the
**                           given bit field, the bit 1 corresponds with
**                           the pin which has index 1 within the given
**                           bit field, etc.
*/
/* ===================================================================*/
void WIFI_XPD_DCDC_INTERRUPT_SetFieldValue(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, WIFI_XPD_DCDC_INTERRUPT_TFieldValue Value)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case INTERRUPT: {                  /* bit field #0 */
      GPIO_PDD_SetPortDataOutput(WIFI_XPD_DCDC_INTERRUPT_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(WIFI_XPD_DCDC_INTERRUPT_MODULE_BASE_ADDRESS)
          & ((WIFI_XPD_DCDC_INTERRUPT_TPortValue)(~((WIFI_XPD_DCDC_INTERRUPT_TPortValue)WIFI_XPD_DCDC_INTERRUPT_INTERRUPT_MASK)))
        )
        | (
          ((WIFI_XPD_DCDC_INTERRUPT_TPortValue)(Value << WIFI_XPD_DCDC_INTERRUPT_INTERRUPT_START_BIT))
          & ((WIFI_XPD_DCDC_INTERRUPT_TPortValue)WIFI_XPD_DCDC_INTERRUPT_INTERRUPT_MASK)
        )
      );
      break;
    }
    default:
      break;                           /* Invalid Field is not treated, result is undefined */
  } /* switch (Field) */
}

/*
** ===================================================================
**     Method      :  WIFI_XPD_DCDC_INTERRUPT_GetFieldValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method returns the current input data of the specified
**         field.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Field           - Bit field to reading. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @return
**                         - Aligned current port input value masked for
**                           allocated pins of the field. The bit 0
**                           corresponds with the pin which has index 0
**                           within the given bit field, the bit 1
**                           corresponds with the pin which has index 1
**                           within the given bit field, etc.
*/
/* ===================================================================*/
WIFI_XPD_DCDC_INTERRUPT_TFieldValue WIFI_XPD_DCDC_INTERRUPT_GetFieldValue(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case INTERRUPT: {                  /* bit field #0 */
      return
        (WIFI_XPD_DCDC_INTERRUPT_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(WIFI_XPD_DCDC_INTERRUPT_MODULE_BASE_ADDRESS)
            & (WIFI_XPD_DCDC_INTERRUPT_TPortValue)WIFI_XPD_DCDC_INTERRUPT_INTERRUPT_MASK
          )
          >> WIFI_XPD_DCDC_INTERRUPT_INTERRUPT_START_BIT
        );
    }
    default:
      break;                           /* Invalid BitField is not treated, result is undefined */
  } /* switch (Field) */
  return (WIFI_XPD_DCDC_INTERRUPT_TFieldValue)0U;
}

/*
** ===================================================================
**     Method      :  WIFI_XPD_DCDC_INTERRUPT_ClearFieldBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method drives the specified bits of the specified bit
**         field to the inactive level.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Mask            - Aligned mask of bits to setting the
**                           inactive level. Each field pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the given
**                           bit field, the bit 1 corresponds with the
**                           pin which has index 1 within the given bit
**                           field, etc.
*/
/* ===================================================================*/
void WIFI_XPD_DCDC_INTERRUPT_ClearFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, WIFI_XPD_DCDC_INTERRUPT_TFieldValue Mask)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case INTERRUPT: {                  /* bit field #0 */
      GPIO_PDD_ClearPortDataOutputMask(WIFI_XPD_DCDC_INTERRUPT_MODULE_BASE_ADDRESS,
        ((WIFI_XPD_DCDC_INTERRUPT_TPortValue)WIFI_XPD_DCDC_INTERRUPT_INTERRUPT_MASK)
        & ((WIFI_XPD_DCDC_INTERRUPT_TPortValue)(Mask << WIFI_XPD_DCDC_INTERRUPT_INTERRUPT_START_BIT))
      );
      break;
    }
    default:
      break;                           /* Invalid Field is not treated, result is undefined */
  } /* switch (Field) */
}

/*
** ===================================================================
**     Method      :  WIFI_XPD_DCDC_INTERRUPT_SetFieldBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method drives the specified bits of the specified bit
**         field to the active level.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Mask            - Aligned mask of bits to setting the
**                           active level. Each field pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the given
**                           bit field, the bit 1 corresponds with the
**                           pin which has index 1 within the given bit
**                           field, etc.
*/
/* ===================================================================*/
void WIFI_XPD_DCDC_INTERRUPT_SetFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, WIFI_XPD_DCDC_INTERRUPT_TFieldValue Mask)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case INTERRUPT: {                  /* bit field #0 */
      GPIO_PDD_SetPortDataOutputMask(WIFI_XPD_DCDC_INTERRUPT_MODULE_BASE_ADDRESS,
        ((WIFI_XPD_DCDC_INTERRUPT_TPortValue)WIFI_XPD_DCDC_INTERRUPT_INTERRUPT_MASK)
        & ((WIFI_XPD_DCDC_INTERRUPT_TPortValue)(Mask << WIFI_XPD_DCDC_INTERRUPT_INTERRUPT_START_BIT))
      );
      break;
    }
    default:
      break;                           /* Invalid Field is not treated, result is undefined */
  } /* switch (Field) */
}

/*
** ===================================================================
**     Method      :  WIFI_XPD_DCDC_INTERRUPT_ToggleFieldBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method inverts the specified bits of the specified bit
**         field to other level.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Mask            - Aligned mask of bits to inverting the
**                           current level. Each field pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the given
**                           bit field, the bit 1 corresponds with the
**                           pin which has index 1 within the given bit
**                           field, etc.
*/
/* ===================================================================*/
void WIFI_XPD_DCDC_INTERRUPT_ToggleFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, WIFI_XPD_DCDC_INTERRUPT_TFieldValue Mask)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case INTERRUPT: {                  /* bit field #0 */
      GPIO_PDD_TogglePortDataOutputMask(WIFI_XPD_DCDC_INTERRUPT_MODULE_BASE_ADDRESS,
        ((WIFI_XPD_DCDC_INTERRUPT_TPortValue)WIFI_XPD_DCDC_INTERRUPT_INTERRUPT_MASK)
        & ((WIFI_XPD_DCDC_INTERRUPT_TPortValue)(Mask << WIFI_XPD_DCDC_INTERRUPT_INTERRUPT_START_BIT))
      );
      break;
    }
    default:
      break;                           /* Invalid Field is not treated, result is undefined */
  } /* switch (Field) */
}

/*
** ===================================================================
**     Method      :  WIFI_XPD_DCDC_INTERRUPT_Interrupt (component GPIO_LDD)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(WIFI_XPD_DCDC_INTERRUPT_Interrupt)
{
  /* {Default RTOS Adapter} ISR parameter is passed through the global variable */
  WIFI_XPD_DCDC_INTERRUPT_TDeviceDataPtr DeviceDataPrv = INT_PORTE__DEFAULT_RTOS_ISRPARAM;
  WIFI_XPD_DCDC_INTERRUPT_TPortValue State;

  State = (WIFI_XPD_DCDC_INTERRUPT_TPortValue)(PORT_PDD_GetInterruptFlags(WIFI_XPD_DCDC_INTERRUPT_PORTCONTROL_BASE_ADDRESS)
          & ((WIFI_XPD_DCDC_INTERRUPT_TPortValue)WIFI_XPD_DCDC_INTERRUPT_ALLOCATED_PINS_MASK)); /* Retrieve flags */
  DeviceDataPrv->EventFlags |= State;
  PORT_PDD_ClearInterruptFlags(WIFI_XPD_DCDC_INTERRUPT_PORTCONTROL_BASE_ADDRESS, State); /* Clears flags */
  WIFI_XPD_DCDC_INTERRUPT_OnPortEvent(DeviceDataPrv->UserData); /* Call OnPortEvent event */
}

/* END WIFI_XPD_DCDC_INTERRUPT. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
