/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : ESP8266_RxBuf.h
**     Project     : clay_demo_esp8266
**     Processor   : MK20DX256VLL7
**     Component   : RingBufferUInt8
**     Version     : Component 01.003, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-09-04, 12:24, # CodeGen: 36
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         Put             - byte ESP8266_RxBuf_Put(byte elem);
**         Get             - byte ESP8266_RxBuf_Get(byte *elemP);
**         NofElements     - byte ESP8266_RxBuf_NofElements(void);
**         NofFreeElements - byte ESP8266_RxBuf_NofFreeElements(void);
**         Init            - void ESP8266_RxBuf_Init(void);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2012, all rights reserved.
**     This an open source software of an embedded component for Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file ESP8266_RxBuf.h
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup ESP8266_RxBuf_module ESP8266_RxBuf module documentation
**  @{
*/         

#ifndef __ESP8266_RxBuf_H
#define __ESP8266_RxBuf_H

/* MODULE ESP8266_RxBuf. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */

#include "Cpu.h"


#define ESP8266_RxBuf_BUF_SIZE   64  /* number of elements in the buffer */


byte ESP8266_RxBuf_Put(byte elem);
/*
** ===================================================================
**     Method      :  ESP8266_RxBuf_Put (component RingBufferUInt8)
**     Description :
**         Puts a new element into the buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**         elem            - New element to be put into the buffer
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

byte ESP8266_RxBuf_Get(byte *elemP);
/*
** ===================================================================
**     Method      :  ESP8266_RxBuf_Get (component RingBufferUInt8)
**     Description :
**         Removes an element from the buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**       * elemP           - Pointer to where to store the received
**                           element
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

byte ESP8266_RxBuf_NofElements(void);
/*
** ===================================================================
**     Method      :  ESP8266_RxBuf_NofElements (component RingBufferUInt8)
**     Description :
**         Returns the actual number of elements in the buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of elements in the buffer.
** ===================================================================
*/

void ESP8266_RxBuf_Init(void);
/*
** ===================================================================
**     Method      :  ESP8266_RxBuf_Init (component RingBufferUInt8)
**     Description :
**         Initializes the data structure
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

byte ESP8266_RxBuf_NofFreeElements(void);
/*
** ===================================================================
**     Method      :  ESP8266_RxBuf_NofFreeElements (component RingBufferUInt8)
**     Description :
**         Returns the actual number of free elements/space in the
**         buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of elements in the buffer.
** ===================================================================
*/

/* END ESP8266_RxBuf. */

#endif
/* ifndef __ESP8266_RxBuf_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
